birdrides/mockingbird

MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/RawType.swift
MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdSupport/Swift/Misc.swift
MockingbirdTests/Framework/InitializerTests.swift

- Adds Swift/Misc.swift supporting source file with AnyObject and `class` type definitions
- Improves unit tests for initializers
Mockingbird was treating class-only protocols (protocols constrained to `AnyObject` or `class`) as an “opaque type” (a referenced type whose source is missing / not parsable). The solution is to include `protocol AnyObject {}` in the `MockingbirdSupport/Swift` supporting source files.
The logic for when to generate an empty designated initializer to use when calling `mock(SomeType.self)` incorrectly excluded class-conforming protocols without checking for existing inherited designated initializers.

Fix class-only protocol initializer generation

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Parser/Cache/CodableTarget.swift
MockingbirdTests/Generator/PBXTargetTests.swift

- Modifies `PBXTarget` `productModuleName` implementation to handle module names with non-alphanumeric characters.
- Adds PBXTargetTests.swift
If Mockingbird generates mocks for a module with non-alphanumeric characters in the name, the generated mocks will not compile.
From [Apple documentation](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c):
> By default, this name is the same as your product name, with any nonalphanumeric characters replaced with an underscore (_). If the name begins with a number, the first digit is replaced with an underscore.

handle non-alphanumeric target names

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdCli/Interface/Generator.swift
MockingbirdCli/Interface/LocalizedError+Extensions.swift

- Use CustomStringConvertible description as errorDescription for ArgumentParserError, ArgumentConversionError, and Generator.Failure.
```
$ mockingbird aa
[ERROR] The operation couldn’t be completed. (SPMUtility.ArgumentParserError error 4.)
$ mockingbird install --aa
[ERROR] The operation couldn’t be completed. (SPMUtility.ArgumentParserError error 0.)
```
```
$ mockingbird aa
[ERROR] expected arguments: version, testbed, uninstall, install, generate
$ mockingbird install --aa
[ERROR] unknown option --aa; use --help to list available options
```

improved cli error messaging

---

.github/workflows/build-framework-cli.yml
Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Utilities/Path+Fnmatch.swift
MockingbirdTests/Generator/PathFnmatchTests.swift

Fixes https://github.com/birdrides/mockingbird/issues/13
Something has changed with the way Swift handles C-style string coercion between macOS Mojave and Catalina. The following correctly encodes and creates a contiguous UTF-8 byte buffer in Mojave that can be passed to `fnmatch`, but breaks in Catalina:
```swift
pattern.data(using: .utf8).withUnsafeBytes({ $0.bindMemory(to: Int8.self).baseAddress })
```
When the encoding is changed to `.ascii` then `fnmatch` magically starts to work in Mojave… even though the `Data` returned is identical to `.utf8` (for the test case which is strictly ASCII).
None of the below work when passed to `fnmatch` in Catalina either:
```swift
pattern.cString(using: .utf8)
pattern.cString(using: .ascii)
pattern.utf8CString
```
The fix is to use the built-in …

Fix fnmatch implementation on macOS Catalina

---

MockingbirdFramework.podspec
README.md

Not all environments (e.g. CI) allow modifying `/usr/local/bin`. Rather than automatically installing the downloaded binary, allow the user to run `$ make install-prebuilt` as needed during the initial set up.

Remove automatic binary installation from pod install prepare_command

---

.github/workflows/build-framework-cli.yml

GitHub Actions is deprecating jobs running on macOS Mojave in favor of just specifying `macOS-latest` as the virtual environment version.

Remove macOS Mojave CI runner

---

MockingbirdCli/Interface/Generator.swift
MockingbirdGenerator/Parser/Cache/CodableTarget.swift
MockingbirdGenerator/Parser/Operations/CheckCacheOperation.swift

CLI version changes can result in breaking changes between the generated mocks and framework, so cached mocks should be invalidated.

Invalidate cached mocked modules when the CLI version changes

---

MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ExtensionsMockableTests.swift
MockingbirdTests/E2E/ExtensionsStubbableTests.swift
MockingbirdTestsHost/Extensions.swift

Previously, flattening inherited types would process each `RawType` partial individually rather than all at once. It was possible that an inherited type with extended declarations could be processed non-deterministically (either via the referencing type or directly).
See also: #19

Include declarations in extensions when flattening inherited types

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework/DSL/TypeFacade.swift
MockingbirdFramework/Mockingbird.swift
MockingbirdFramework/Verification/Invocation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ClosureParametersStubbableTests.swift
MockingbirdTests/Framework/ClosureParameterTests.swift
MockingbirdTestsHost/ClosureParameters.swift

Allow `any()` and `notNil()` to match non-escaping closures without additional boilerplate and fix memory management regression in type facade when wrapping closures and other implicitly retained types.
See also: https://birdopensource.slack.com/archives/CNR21LQCW/p1575076093002000

Fix matching closures with wildcard argument matchers

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/GenericType.swift
MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/RawType.swift
MockingbirdGenerator/Parser/Models/TypeAttributes.swift
MockingbirdGenerator/Parser/Operations/ParseFilesOperation.swift
MockingbirdGenerator/Utilities/Log.swift
MockingbirdGenerator/Utilities/OperationQueue+Extensions.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ExternalModuleTypesMockableTests.swift
MockingbirdTests/E2E/ExternalModuleTypesStubbableTests.swift
MockingbirdTests/Framework/InitializerTests.swift
MockingbirdTestsHost/ExternalModuleTypes.swift
MockingbirdTestsHost/Module/Generics.swift

- Improve handling of types and constraints inherited from grandparents
- Parse imports from all source and dependency files
- De-dup generic where clause constraints
- Add access level checks on inherited members from external modules
- Improve logging for default empty initializer generation and add warnings when attempting to mock uninitializable protocols
(Fixes #22)

Improve handling of members from external modules

---

Mockingbird.xcodeproj/project.pbxproj

and remove absolute paths when running mocks generation

add MockingbirdCli as a dependency to MockingbirdTests

---

MockingbirdFramework/DSL/TypeFacade.swift
MockingbirdFramework/Stubbing/StubbingContext.swift
MockingbirdFramework/Stubbing/TestKiller.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/Framework/ArgumentCaptorTests.swift
MockingbirdTests/Framework/ArgumentMatchingTests.swift
MockingbirdTestsHost/ArgumentMatching.swift

Value witness table for protocol'd structs breaks the unsafe pointee approach. Using a temporary execution context for runtime resolution of type facade closures is safer and more robust.
Fixes #33

Rewrite type facade to use execution context approach

---

MockingbirdGenerator/Parser/Models/MethodParameter.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/Framework/ClosureParameterTests.swift
MockingbirdTestsHost/ClosureParameters.swift

Closures wrapped in a single element tuple are non-escaping, but closures wrapped in a multiple element tuple are escaping.
Fixes #36

Handle closure parameters wrapped in a single element tuple

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Utilities/String+Extensions.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/KeywordArgumentNamesMockableTests.swift
MockingbirdTests/E2E/KeywordArgumentNamesStubbableTests.swift
MockingbirdTests/Generator/StringExtensionsTests.swift
MockingbirdTestsHost/KeywordArgumentNames.swift

Fixes #35 where escaped keywords in parameter names do not get escaped in the generated mock code.
I believe `inout` is the only keyword (in param names) that backticks are needed for in the current version of swift, however this fix will work for any future keywords as well.

Add support for keyword parameter names

---

MockingbirdGenerator/Utilities/Path+Fnmatch.swift
MockingbirdTests/Generator/PathFnmatchTests.swift

> Excluding Files
> You can exclude unwanted or problematic sources from being mocked by adding a .mockingbird-ignore file. Mockingbird follows the same pattern format as .gitignore and scopes ignore files to their enclosing directory.
`.gitignore` is not using `FNM_PERIOD` rule.

Match dot files with a wildcard in ignore rules

---

MockingbirdGenerator/Parser/Operations/ProcessTypesOperation.swift
MockingbirdSupport/Foundation/ObjectiveC/NSObject.swift

Also update `NSObject` supporting source declaration to include `init`
**PR stack:** 1/2

Log warning when trying to mock a non-initializable class

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Generator/Extensions/Attributes+Sanitize.swift
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/VariableTemplate.swift
MockingbirdGenerator/Parser/Operations/ProcessTypesOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdSupport/Foundation/ObjectiveC/NSObject.swift
MockingbirdTestsHost/DeclarationAttributes.swift

The attribute is implicitly added to overriding declarations when subclassing or satisfying a protocol with the objc attribute.
Fixes #38 
**PR stack:** 2/2 (depends on #44)

Ignore objc attributes for all generated hooks

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Parser/Cache/CodableTarget.swift

Check both `PRODUCT_MODULE_NAME` and `PRODUCT_NAME` values in build settings and recursively resolve any build setting values.
Fixes #28

Improve target module name resolving

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework/Mockingbird.swift
MockingbirdFramework/Verification/Verification.swift
MockingbirdTests/Framework/CountMatcherTests.swift

Nominal count matchers {`never`, `once`, `twice`} are now just `UInt` aliases which allows them to be passed directly into inequality count matchers like `atLeast`. This makes things a bit more readable:
`verify(foo.bar()).wasCalled(atLeast(1))`
becomes
`verify(foo.bar()).wasCalled(atLeast(once))`

Improve integration of nominal count matchers

---

MockingbirdFramework/Matching/ArgumentMatcher.swift
MockingbirdFramework/Mockingbird.swift
MockingbirdFramework/Verification/Invocation.swift
MockingbirdFramework/Verification/TestFailure.swift
MockingbirdFramework/Verification/Verification.swift

Test failures now report all recorded invocations to that particular selector and make the expected invocation count clearer:
```
Got 0 invocations of 'chirp(volume: Int) -> Void' with arguments [42]
but expected n ≥ 2
All invocations of 'chirp(volume: Int) -> Void':
(1) 'chirp(volume: Int) -> Void' with arguments [1]
(2) 'chirp(volume: Int) -> Void' with arguments [2]
(3) 'chirp(volume: Int) -> Void' with arguments [3]
```

Improve clarity and verboseness of test failure messages

---

MockingbirdFramework/DSL/TypeFacade.swift

Types conforming to `Equatable` are losing static type information and transforming into `Any?` upon resolution. This currently doesn’t (seem to) break anything because type information is restored from the mocked call site and previous argument matchers are coerced at verification time into the right type.

Fix type coercion regression in type facade resolution method

---

MockingbirdGenerator/Generator/FileGenerator.swift

The initializer template uses lazy computed properties from the mockable type template which aren't thread-safe.

Fix thread safety issue with template rendering

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework/Mockingbird.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/Framework/FloatingPointMatcherTests.swift
MockingbirdTestsHost/ArgumentMatching.swift
README.md

Usage: `around(10.0, tolerance: 0.01)`

Add fuzzy floating point matcher to standard testing library

---

MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/Framework/InitializerTests.swift
MockingbirdTestsHost/ClassOnlyProtocols.swift

Class constrained protocols come in a few flavors:
(1) Constrained on a class that defines a designated initializer
(2) Constrained on a class that doesn't define a designated initializer
For (1), any additional initializers declared by the class-constrained protocol are now disabled at compile time with `@available` and at runtime with `fatalError()`.
For (2), concrete protocol initializer implementations instead call the default empty superclass initializer.

Handle class-constrained protocols with designated initializers

---

Makefile
Mockingbird.xcodeproj/project.pbxproj
MockingbirdCli/Interface/ArgumentParser+Extensions.swift
MockingbirdCli/Interface/Commands/GenerateCommand.swift
MockingbirdCli/Interface/Commands/InstallCommand.swift
MockingbirdCli/Interface/Generator.swift
MockingbirdCli/Interface/Installer.swift
MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdGenerator/Parser/Operations/ProcessTypesOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ExternalModuleTypesMockableTests.swift
MockingbirdTests/E2E/ExternalModuleTypesStubbableTests.swift
MockingbirdTestsHost/ExternalModuleImplicitlyImportedTypes.swift
MockingbirdTestsHost/MockingbirdTestsHost.h
MockingbirdTestsHost/Module/ObjectiveC.swift
README.md

ObjC interoperability allows `@objc` marked types to be implicitly imported in Swift files without an import declaration. Given a type declared as `@objc(MKBFoo) public protocol Foo {}` in ModuleA, it's possible for ModuleB to declare a header that imports ModuleA's ObjC generated interface header `#import <ModuleA/ModuleA-Swift.h>`.
ModuleB can then use `Foo` in any Swift files without declaring `import ModuleA` (!!)
The simple fix here relaxes the "linker" by allowing type resolution on any of the module dependencies. Modules explicitly imported from an import declaration are searched first (on a per-file basis). It's worth noting that relaxed linking allows _all_ types to be resolved implicitly not just those marked as `@objc`.
If needed, relaxed linking can be disabled with the …

Handle implicitly imported modules in mixed-source targets

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Parser/Cache/CodableTarget.swift

Build settings dictionary exposed by XcodeProj does not contain certain implicit build settings such as `TARGET_NAME`, which breaks product module name resolution.
The fallback product module name now defaults to the sanitized target name only.
Fixes #28

Support implicit TARGET_NAME build setting for module name resolution

---

MockingbirdFramework/Mockingbird.swift

Adds convenience methods to `or`, `and`, `xor`, and `not`
(Stack 1 of 2)

Fix backwards compatibility for compound nominal count matchers

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework/Matching/CountMatcher.swift
MockingbirdFramework/Mocking/MockingContext.swift
MockingbirdFramework/Mockingbird.swift
MockingbirdFramework/Stubbing/TestKiller.swift
MockingbirdFramework/Verification/AsyncVerification.swift
MockingbirdFramework/Verification/Invocation.swift
MockingbirdFramework/Verification/OrderedVerification.swift
MockingbirdFramework/Verification/TestFailure.swift
MockingbirdFramework/Verification/Verification.swift
MockingbirdFramework/Verification/XCTFailSwizzler.swift
MockingbirdTests/Framework/AsyncVerificationTests.swift
MockingbirdTests/Framework/OrderedVerificationTests.swift
MockingbirdTests/Framework/Utilities/XFailBaseTestCase.swift
MockingbirdTests/Framework/Utilities/XFailTestFailer.swift
MockingbirdTests/Framework/XFailOrderedVerificationTests.swift
README.md

(Stack 2 of 2)
Closes #48
- Refactor `AsyncVerificationGroup` into generalized `ExpectationGroup`
- Add `inOrder` verification group to DSL
- Add XFail infrastructure for asserting test cases should emit XCTFail
Basic example usage of `inOrder`:
```swift
// Given
let bird = mock(Bird.self)
// When
(bird as Bird).fly()
(bird as Bird).chirp()
// Then
inOrder {
verify(bird.fly()).wasCalled()
verify(bird.chirp()).wasCalled()
}
```
Ordered verification is greedy, so the following would _fail_:
```swift
// Given
let bird = mock(Bird.self)
// When
(bird as Bird).fly()
(bird as Bird).chirp()
(bird as Bird).fly()
(bird as Bird).fly()
(bird as Bird).chirp()
(bird as Bird).chirp()
(bird as Bird).fly()
// Then
inOrder {
verify(bird.fly()).wasCalled()
verify(bird.chirp()).wasCalled(twice) …
```

Add in order verification for enforcing relative invocation ordering

---

MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeInitializerTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/RawType.swift
MockingbirdGenerator/Parser/Models/SerializationRequest.swift
MockingbirdGenerator/Parser/Operations/ProcessStructuresOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTestsHost/Generics.swift

Prerequisite to fixing #62
Fixes generic types that shadow nominal types, which would cause invalid module namespacing:
```swift
struct ShadowedType {}
class MyClass<ShadowedType> {
// Used to result in MyModule.ShadowedType
func method(param: ShadowedType) {}
}
```
Also fixes generic type shadowing in nested classes, which would break generated class `mock` initializers:
```swift
class OuterClass<T> {
class InnerClass<T> {
func method(param: T) {}
}
}
```

Handle generic type shadowing

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/Method.swift
MockingbirdGenerator/Parser/Models/MethodParameter.swift
MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/Parser/Single.swift
MockingbirdGenerator/Parser/Models/RawType.swift
MockingbirdGenerator/Parser/Models/SerializationRequest.swift
MockingbirdGenerator/Parser/Models/Specializable.swift
MockingbirdGenerator/Parser/Models/Variable.swift
MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTestsHost/Generics.swift

Fixes #62
Generic type specialization requires mapping from some declared generic type parameter to another type, e.g. mapping `T` to `Bool`:
```swift
// Subclass implicitly has `func method(param: Bool) -> Bool`
class Base<T> {
func method(param: T) -> T
}
class Subclass: Base<Bool> {}
```
This of course also holds true when mapping to a generic type defined by the subclass instead of a nominal type.
```swift
// Subclass implicitly has `func method(param: R) -> R`
class Base<T> {
func method(param: T) -> T
}
class Subclass<R>: Base<R> {}
```
With shadowing, mapping to the correct fully qualified type becomes slightly more complex. For example, the generic type from the subclass can shadow valid module-level types.
```swift
class Base<T> {
func method(param: T) -> T
}
class …
```

Specialize members inherited from generic classes

---

Documentation/ManualSetup.md
README.md

**(Stack 2 of 5)**
- Add troubleshooting section with common problems and fixes
- Streamline setup section to only include happy path CLI installer
- Move manual installation documentation to separate page
- Surface need for installing supporting source files during setup
- Add overview section with high level summary
- Provide direct links to starter supporting source files and precompiled artifacts
- Expand on using closures for stubbing complex logic
- Move matching literals and objects to top of argument matching section and differentiate between each type

[2/5] Improve clarity of setup and installation process in README

---

Examples/iOSMockingbirdExample-Carthage/Cartfile
MockingbirdFramework/Mocking/Mock.swift
MockingbirdGenerator/Generator/FileGenerator.swift
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeInitializerTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Utilities/Array+Extensions.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ExternalModuleClassScopedTypesMockableTests.swift
MockingbirdTests/E2E/InitializersMockableTests.swift
MockingbirdTestsHost/ClassScopedTypes.swift
README.md

TL;DR Compile time errors + better semantics for mocks vs dummy objects.
A common error is coercing the value returned from `mock` into its supertype, e.g. `let bird: Bird = mock(Bird.self)`. This breaks stubbing and verification functions which rely on methods defined in the concrete mock type.
Other testing frameworks get around this by using direct mock type initialization, e.g. `let bird = BirdMock()`, which is less likely to be mistakenly coerced. However, it’s marginally less intuitive for protocol mocks, slightly more intuitive for class mocks that require initialization, but significantly worse when surfacing errors from missing stubbed implementations.
Providing compile time errors that stop undesired type coercion and uninitialized class mocks will improve initial developer …

Enforce correct usage of class and protocol mocks

---

.github/workflows/build-framework-cli.yml
Makefile

Include prebuilt iOS, macOS, tvOS framework in release artifacts
- Build framework for all platforms: `make build-framework`
- Build framework for macOS: `make build-framework-macos`
- Build framework for iOS: `build-framework-iphonesimulator`
- Build framework for tvOS: `build-framework-appletvsimulator`
- Build framework and CLI: `make build`

Include prebuilt iOS, macOS, tvOS framework in release artifacts

---

Documentation/MockingExternalTypes.md
README.md

In the future, supporting source files should be downloadable via the CLI as part of the install step or even have its own command. But for now, simply having better documentation should suffice.

Clarify documentation on how to use supporting source files

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Parser/Sourcery/InferType.swift
MockingbirdGenerator/Utilities/String+Extensions.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/VariablesMockableTests.swift
MockingbirdTests/E2E/VariablesStubbableTests.swift
MockingbirdTests/Generator/InferTypeTests.swift
MockingbirdTestsHost/Variables.swift

This fixes a small bug where type was not being inferred from code such as:
var storedVariableWithConstructedImplicitType = Bool(booleanLiteral: true)
Problem was that the `inferType(..)` code was trying to split on the first `(` character, but was also including `()` in groups to ignore. I think it's safe to do the split only excluding <> and [] groups--can't think of any other case where a `(` would not delineate the type from its init params (tuples are handled by earlier code paths).

Fixed instance var type inference for initialized types

---

MockingbirdFramework/Matching/ArgumentMatcher.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/Method.swift
MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/TypeAttributes.swift
MockingbirdGenerator/Parser/Models/Variable.swift
MockingbirdGenerator/Parser/Operations/ProcessStructuresOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/GenericsMockableTests.swift

- Access level for extended members returned by SourceKit are no longer explicitly marked as `internal`
- Remove memory address printing for types matched by reference due to bad invocation error when handling optional strings
- Generate generically overloaded methods wrapped in `#if swift(>=5.2)`

Fix compatibility with Swift 5.2

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework/Mocking/Mock.swift
MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
MockingbirdGenerator/Parser/Models/TypeAttributes.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTests/E2E/ChildMockStubbableTests.swift
MockingbirdTests/E2E/ChildProtocolMockStubbableTests.swift
MockingbirdTests/E2E/ClassScopedTypesStubbableTests.swift
MockingbirdTests/E2E/ClosureParametersStubbableTests.swift
MockingbirdTests/E2E/DefaultArgumentValuesStubbableTests.swift
MockingbirdTests/E2E/ExceptionsStubbableTests.swift
MockingbirdTests/E2E/ExtensionsStubbableTests.swift
MockingbirdTests/E2E/ExternalModuleTypesStubbableTests.swift
MockingbirdTests/E2E/GenericsStubbableTests.swift
MockingbirdTests/E2E/InoutParametersStubbableTests.swift
MockingbirdTests/E2E/KeywordArgumentNamesStubbableTests.swift
MockingbirdTests/E2E/SubscriptMockableTests.swift
MockingbirdTests/E2E/SubscriptStubbableTests.swift
MockingbirdTests/E2E/TypealiasingStubbableTests.swift
MockingbirdTests/E2E/UndefinedArgumentLabelsStubbableTests.swift
MockingbirdTests/E2E/VariadicParametersStubbableTests.swift
MockingbirdTests/Framework/SubscriptTests.swift
MockingbirdTestsHost/Subscripts.swift
README.md

Closes #31
Similar to properties, subscripts require synthetic construction of getters and setters. Although subscripts have `get` and `set` handlers, they can define (multiple) parameters and are parsed as methods, making it a slight variant on the typical method handling.
```swift
protocol SubscriptedProtocol {
subscript(row: Int, col: Int) -> String { get set }
}
```
The above roughly produces the following mock code:
```swift
class SubscriptedProtocolMock {
// Mocked implementation
override subscript(row: Int, col: Int) -> String {
get {
// ...
}
set {
// ...
}
}
// Matchable implementation
func getSubscript(row: Int, col: Int) -> String {
// ...
}
func setSubscript(row: Int, col: Int, newValue: String) {
// ...
}
}
```
Which can then be tested with similar syntax to properties. The …

Add support for subscripts

---

MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/TypeAttributes.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTestsHost/OpaqueTypes.swift

Certain methods like `init(from:)` in `Decodable` can be synthesized by the Swift compiler and don't require explicit conformance. For initializers specifically, these synthesized methods can be inherited by subclasses _unless_ the subclass defines a designated initializer of its own or overrides the superclass' designated initializer.
Fixes #87

Fix classes with designated + implicitly synthesized initializers

---

MockingbirdFramework/Mocking/MockingContext.swift
MockingbirdFramework/Stubbing/StubbingContext.swift
MockingbirdFramework/Stubbing/ValueProvider.swift
MockingbirdFramework/Utilities/Synchronized.swift
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/Typealias.swift
MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdGenerator/Parser/Operations/ParseSingleFileOperation.swift
MockingbirdGenerator/Utilities/Deallocation.swift
MockingbirdGenerator/Utilities/Synchronized.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift

This was leading to very rare and hard to reproduce crashes in release builds. Adds a `read` method on the `Synchronized` class for thread-safe reading of synchronized collection types.

Fix collection types not being properly synchronized

---

MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/RawType.swift
MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTestsHost/OpaquelyInheritedTypes.swift

Remove mutable opaque inherited type names from `RawType` and move into `MockableType` initialization instead.

Fix thread-safety issues with opaque inherited type names

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
MockingbirdGenerator/Parser/Models/MockableType.swift
MockingbirdGenerator/Parser/Models/Variable.swift
MockingbirdGenerator/Parser/Operations/ProcessTypesOperation.swift
MockingbirdMocks/MockingbirdTestsHostMocks.generated.swift
MockingbirdTestsHost/ConflictingProtocolProperties.swift

Adds check for inherited property names that conflict with other declarations, specifically for protocols.
```swift
protocol InheritedConflictingProtocolProperties {
var foo: Bool { get set }
var bar: Bool { get set }
}
// Not possible to create a class conforming to any of the protocols below.
protocol SingleConflictingProtocolProperties: InheritedConflictingProtocolProperties {
var foo: String { get set }
}
protocol MultipleConflictingProtocolProperties: SingleConflictingProtocolProperties {
var foo: Int { get set }
var bar: Int { get set }
}
```
Consolidates `.notMockable` diagnostic warnings into the rendering step.

Generate availability attributes for unmockable top-level types

---

MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift

Fixes message not being deterministic between runs

Sort conflicting property names in generated availability attribute

---

MockingbirdFramework/Verification/Invocation.swift
MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift
MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
MockingbirdGenerator/Generator/Templates/VariableTemplate.swift
MockingbirdTests/Framework/OverloadedMethodTests.swift
MockingbirdTestsHost/OverloadedMethods.swift

Fix verification for methods overloaded via generic return type
This was causing all invocations to methods with generic return types to be treated as returning the same type.
```swift
protocol MyProtocol {
func genericMethod<T>() -> T
}
let myMock = mock(MyProtocol.self)
given(myMock.genericMethod()) ~> "Foo"
given(myMock.genericMethod()) ~> true
let foo: String = (myMock as MyProtocol).genericMethod()
let bar: Bool = (myMock as MyProtocol).genericMethod()
// Invocation counts for both were incorrectly 2 instead of 1
verify(myMock.genericMethod()).returning(String.self).wasCalled()
verify(myMock.genericMethod()).returning(Bool.self).wasCalled()
```
Fix is to also store the actual type returned at runtime in order to differentiate invocations to the same generic method.

Fix verification for methods overloaded via generic return type

---

Mockingbird.xcodeproj/project.pbxproj
MockingbirdGenerator/Parser/Models/GenericType.swift
MockingbirdGenerator/Parser/Models/Method.swift
MockingbirdGenerator/Parser/Models/MethodParameter.swift
MockingbirdGenerator/Parser/Models/Variable.swift
MockingbirdGenerator/Parser/Operations/ProcessStructuresOperation.swift
MockingbirdTestsHost/DuplicateProtocolMembers.swift

Fixes #118 
- Remove `MethodParameter` parameter names and other extraneous parsed info from hashed value
- Add considerations for generic same type requirement which is commutative and can have "swapped" lhs and rhs type identifiers

Fix uniqueness and equality operators for parsed type models

---

MockingbirdFramework/Mockingbird.swift
MockingbirdFramework/Stubbing/Stubbing.swift
MockingbirdFramework/Stubbing/StubbingContext.swift
MockingbirdTests/Framework/SequentialValueStubbingTests.swift
README.md

Closes #111 
Implementation closures follow the same principle as normal closure stubs that use the stubbing operator directly.
```swift
given(bird.getName()) ~> sequence(of: {
return "Ryan"
}, {
return "Sterling"
}, {
return Bool.random() ? "Ryan" : "Sterling"
})
```
This replaces non-parameterized lazy sequential value stubbing in 0.12.

Add support for stubbing a sequence of implementations using closures

---

Examples/iOSMockingbirdExample-Carthage/README.md
Examples/iOSMockingbirdExample-CocoaPods/README.md
Examples/iOSMockingbirdExample-SPM/README.md
Makefile
MockingbirdCli/Interface/Commands/InstallCommand.swift
MockingbirdCli/Interface/Program.swift
MockingbirdCli/main.swift
README.md

Also removes building framework from source in README. Will be moved to wiki along with best practices for Module Stability and CI integration.

Simplify installation instructions in README

---

Sources/MockingbirdGenerator/Parser/Models/InferType.swift
Sources/MockingbirdGenerator/Parser/Models/SerializationRequest.swift
Sources/MockingbirdTestsHost/ImplicitVariableTypes.swift
Tests/E2E/ImplicitVariableTypesMockableTests.swift
Tests/Generator/InferTypeTests.swift

Previously `MyType().property` would be incorrectly inferred as an enum.
Note that enum cases are syntactically the same as static properties (or methods in the case of enums with associated types). It's not 100% safe to infer the type without additional semantic info.

Improve type inference for enums

---

Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdFramework/Stubbing/StubbingContext.swift
Sources/MockingbirdFramework/Utilities/CwlDemangle.swift
Sources/MockingbirdFramework/Utilities/StackTrace.swift
Sources/MockingbirdFramework/Utilities/String+Extensions.swift
Sources/MockingbirdFramework/Verification/Invocation.swift
Sources/MockingbirdFramework/Verification/TestFailure.swift
Sources/MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
Sources/MockingbirdGenerator/Utilities/String+Components.swift

⚠️ Stacked on #138 and #141 ⚠️ 
Adds a stack trace and examples of how to stub the declaration. The stack trace requires demangling Swift symbols which is done using [CwlDemangle](https://github.com/mattgallagher/CwlDemangle) until Swift gains built-in support for symbol demangling.
```
failed - Missing stubbed implementation for 'childParameterizedInstanceMethod(param1: Bool, _ param2: Int) -> Bool' with arguments [true, 1]
Make sure the method has a concrete stub or a default value provider registered with the return type.
Examples:
given(someMock.childParameterizedInstanceMethod(…)).willReturn(someValue)
given(someMock.childParameterizedInstanceMethod(…)).will { return someValue }
someMock.useDefaultValues(from: .standardProvider)
Stack trace:
(0) [MockingbirdTests] …
```

Improve missing stub implementation test failure message

---

.github/workflows/build-framework-cli.yml
.github/workflows/test-example-projects.yml
Makefile
Sources/MockingbirdGenerator/Parser/Models/GenericType.swift
Sources/MockingbirdGenerator/Parser/Models/Method.swift

⚠️ Stacked on #141 and #142 ⚠️ 
Inconsistent generated mock files are generally benign as mocks aren't checked in and caching logic only depends on on input / source file consistency.
However, in an effort to make builds 100% reproducible, we now test for output (and test) flakiness in the CI.

Fix missing return type in ordering logic

---

Mockingbird.xcodeproj/project.pbxproj
README-0.14.md
README.md
Sources/MockingbirdFramework/Mocking/Mocking.swift
Sources/MockingbirdGenerator/Generator/Templates/MockableTypeInitializerTemplate.swift

- Disambiguates concrete vs abstract return types from `mock(…)`
- Adds fallback with descriptive error message for unmocked types

Improve documentation for mocking types

---

.github/workflows/build-framework-cli.yml
README-0.14.md
Sources/MockingbirdCli/Interface/ArgumentParser+Extensions.swift
Sources/MockingbirdCli/Interface/Commands/GenerateCommand.swift
Sources/MockingbirdCli/Interface/Commands/InstallCommand.swift
Sources/MockingbirdCli/Interface/Generator+PruningPipeline.swift
Sources/MockingbirdCli/Interface/Generator.swift
Sources/MockingbirdCli/Interface/Installer.swift
Sources/MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/VariableTemplate.swift
Sources/MockingbirdGenerator/Parser/Operations/CheckCacheOperation.swift
Sources/MockingbirdGenerator/Parser/Project/CodableTarget.swift
Sources/MockingbirdGenerator/Parser/Project/SourceTarget.swift
Sources/MockingbirdTestsHost/Generics.swift

- The source root for thunk pruning should be obtained from the build environment during test bundle compilation instead of the argument values passed to the generator.
- Improves documentation and messaging around thunk stubs.

Fix source root derivation for thunk pruning

---

Sources/MockingbirdCli/Interface/Commands/DownloadCommand.swift
Sources/MockingbirdCli/Interface/Commands/InstallCommand.swift
Sources/MockingbirdCli/Interface/Commands/TestbedCommand.swift
Sources/MockingbirdCli/Interface/Commands/UninstallCommand.swift
Sources/MockingbirdCli/Interface/Commands/VersionCommand.swift
Sources/MockingbirdGenerator/Generator/Operations/GenerateFileOperation.swift
Sources/MockingbirdGenerator/Utilities/Log.swift

Replaces `print("message")` with `logInfo("message")` which enforces output ordering of printed statements relative to debug logs, errors, and warnings.

Add info logging level for printing to stdout

---

Sources/MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
Sources/MockingbirdGenerator/Parser/Operations/TestFileParser.swift

Mock type references are now stripped of generic types during parsing and before comparison.
Fixes #155

Fix thunk stub generation for generic types

---

Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdGenerator/Generator/Templates/MockableTypeInitializerTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
Sources/MockingbirdGenerator/Parser/Operations/TestFileParser.swift
Sources/MockingbirdTestsHost/Generics.swift
Tests/MockingbirdTests/E2E/GenericsMockableTests.swift
Tests/MockingbirdTests/E2E/GenericsStubbableTests.swift
Tests/MockingbirdTests/E2E/TypealiasingMockableTests.swift
Tests/MockingbirdTests/Framework/GenericsTests.swift
Tests/MockingbirdTests/Framework/StubbingTests.swift

⚠️ Stacked on #156 ⚠️ 
Previously, generic classes and protocols required passing the generated mock metatype for initialization which was differed from non-generic mock initialization. This is now unified such that initialization always takes in the original metatype.
```swift
// Old
mock(MyGenericTypeMock<SomeType>.self)
// New
mock(MyGenericType<SomeType>.self)
```
For protocols, this requires shadowing the original type with an uninhabited enum. Although this could introduce ambiguity in test cases that reference the original type in a generic type constraint, the incidence should be quite low and users can resolve it by simply prefixing the type name with its module qualification.
Closes #154

Unify generic mock init and fix thunk stubs

---

Sources/MockingbirdFramework/Stubbing/DefaultValues.swift
Sources/MockingbirdFramework/Stubbing/ValueProvider+Collections.swift
Sources/MockingbirdFramework/Stubbing/ValueProvider+Foundation.swift
Sources/MockingbirdFramework/Stubbing/ValueProvider+Tuples.swift
Sources/MockingbirdFramework/Stubbing/ValueProvider.swift
Sources/MockingbirdFramework/Verification/Invocation.swift
Tests/MockingbirdTests/Framework/DefaultValueProviderTests.swift

Simplifies `ValueProvider` by removing the previous ability to hierarchically compose providers. This change better aligns `ValueProvider` with the Swift collection APIs.
```swift
// Old
var provider = ValueProvider()
provider.addSubprovider(.standardProvider)
provider.removeSubprovider(.standardProvider)
// New (mutating)
var provider = ValueProvider()
provider.add(.standardProvider)
// New (non-mutating)
let provider = ValueProvider.collectionsProvider
.adding(.primitivesProvider)
// New (non-mutating w/ sugar)
let provider = .collectionsProvider + .primitivesProvider
```

Improve ValueProvider value semantics

---

.github/workflows/release.yml
.xcode/xcconfigs/MockingbirdFramework.xcconfig
Codesigning/MockingbirdCli.dr
Makefile

Optionally uses `altool` in the signed release pipeline to notarize artifacts and adds a release job to the CI which generates signed artifacts on master and release pushes.
Note: This updates the pinned designated requirement to the `Developer ID Installer` and `Developer ID Application` certificate types for Bird Rides, Inc (P2T4T6R4SL).

Update code signing to notarize package and zipped CLI binary

---

Mockingbird.xcodeproj/project.pbxproj
README-0.16.md
Sources/MockingbirdCli/Interface/ArgumentParser+Extensions.swift
Sources/MockingbirdCli/Interface/Commands/GenerateCommand.swift
Sources/MockingbirdCli/Interface/Generator+Pipeline.swift
Sources/MockingbirdCli/Interface/Generator+PruningPipeline.swift
Sources/MockingbirdCli/Interface/Generator.swift
Sources/MockingbirdGenerator/Parser/Project/CodableTarget.swift
Sources/MockingbirdGenerator/Parser/Project/Project.swift
Sources/MockingbirdGenerator/Parser/Project/ProjectDescription.swift
Sources/MockingbirdGenerator/Parser/Project/TargetType.swift

⚠️ Stack **1 of n** ⚠️ 
Custom build systems such as Buck or Bazel need a way to generate mocks without an `.xcodeproj` file. This adds support for passing a JSON project description containing all of the required module and dependency graph information usually parsed from an Xcode project. The description format is roughly compatible with the output from `$ swift package describe --type JSON`, although adding the `dependency` field needs to be upstreamed.
```json
{
"targets": [
{
"name": "MyLibrary",
"type": "library",
"path": "/path/to/my-library",
"dependencies": [],
"sources": [
"SourceFileA.swift",
"SourceFileB.swift"
]
},
{
"name": "MyOtherLibrary",
"type": "library",
"path": "/path/to/my-other-library",
"dependencies": [
"MyLibrary"
],
"sources": [
"SourceFileA.swift", …
```

[1/n] Add support for reading JSON project descriptions

---

Sources/MockingbirdCli/Interface/Generator+Pipeline.swift
Sources/MockingbirdCli/Interface/Generator+PruningPipeline.swift
Sources/MockingbirdCli/Interface/Generator.swift

This PR adds `targetName` to the lock file name, to make sure cache doesn't get invalidated when generating mocks for a different target.
It fixes issue https://github.com/birdrides/mockingbird/issues/191

Add targetName to lock file name

---

README.md
Sources/MockingbirdCli/Interface/ArgumentParser+Extensions.swift
Sources/MockingbirdCli/Interface/Commands/DownloadCommand.swift

In order to cache the mockingbird package on a local server and downloading it from there, the hardcoded github link must be changeable.
I havn't tried this MR locally so please review it.
Link to my already created Feature Request: https://github.com/birdrides/mockingbird/issues/200

Added possibility to change the download URL

---

.github/workflows/test-example-projects.yml
Examples/iOSMockingbirdExample-Carthage/README.md
Examples/iOSMockingbirdExample-Carthage/iOSMockingbirdExample-Carthage.xcodeproj/project.pbxproj
Makefile

XCFrameworks are required for Xcode 12 compatibility due to Carthage building fat libraries for both simulator and device.

Update Carthage example project to XCFrameworks

---

.github/workflows/build-framework-cli.yml
.github/workflows/release.yml
.gitignore
Makefile
README-0.17.md
README.md
Sources/MockingbirdCli/Interface/Commands/InstallCommand.swift
mockingbird

Most devs currently don’t pin the CLI because it’s not part of the happy path in the setup instructions. Devs that do decide to pin the CLI usually do so by checking it into source control which is not sustainable long term.
This change makes pinning the binary part of the happy path of setting up the framework for all package managers by adding a “launcher” to abstract the CLI initialization process. The launcher allows the CLI to be downloaded on-demand from an artifact provider. By default, GitHub’s release artifacts is used, but it’s possible to set the download URL at various levels:
- `REPO_URL` for artifacts hosted on a forked GitHub repo
- `ARTIFACTS_URL` for versioned artifacts at `/<version>/Mockingbird.zip`
- `ZIP_RELEASE_URL` for artifacts at arbitrary URLs
A side effect of …

Add versioned CLI launcher

---

Sources/MockingbirdGenerator/Generator/Operations/FileGenerator.swift
Sources/MockingbirdGenerator/Generator/Operations/GenerateFileOperation.swift
Sources/MockingbirdGenerator/Parser/Models/ParsedFile.swift
Sources/MockingbirdGenerator/Parser/Operations/ParseFilesOperation.swift
Sources/MockingbirdGenerator/Parser/Operations/ParseSingleFileOperation.swift
Sources/MockingbirdGenerator/Parser/Operations/ProcessTypesOperation.swift
Sources/MockingbirdGenerator/Parser/Operations/SourceFileAuxiliaryParser.swift
Sources/MockingbirdTestsHost/CompilationDirectives.swift

Some source modules conditionally gate import declarations via compilation directives to support platform-specific dependencies. This change allows import declarations in the generated mock file to preserve compilation directives from the original source file.
Closes #184

[3/n] Support imports gated by compilation directives

---

.github/workflows/build-framework-cli.yml
Mockingbird.xcodeproj/project.pbxproj
README-0.17.md
Sources/MockingbirdCli/Interface/Commands/GenerateCommand.swift

Although the parser+generator is relatively mature, the surface area of source changes with the potential to cause broken generated mocks is still quite large. To improve the developer experience and initial setup process, this change flips the default thunk pruning level from 'stub' which still generates *declarations* for unused types, to 'omit' which only creates mocks for referenced types in tests.
See also: https://github.com/birdrides/mockingbird/pull/174

[3/n] Change default thunk pruning level to 'omit'

---

Sources/MockingbirdGenerator/Parser/Models/MockableType.swift
Tests/MockingbirdTests/E2E/ExtensionsMockableTests.swift
Tests/MockingbirdTests/E2E/ExtensionsStubbableTests.swift

Although methods defined in protocol extensions can be re-defined in a conforming type, static dispatch means that the original method will always be called. Currently the generator creates mocking code for protocol extensions which was leading to unexpected results in tests for stubbing and verification.

[3/n] Remove protocol extension methods

---

Sources/MockingbirdGenerator/Parser/Models/Function.swift
Tests/MockingbirdTests/Generator/DeclaredTypeTests.swift

Function parameter attributes without whitespace between the attribute and the type annotation currently fail to parse correctly, e.g.
```swift
func foo(bar: @escaping(String) -> Void)
func foo(bar: @escaping@autoclosure() -> String)
```

[3/n] Improve parsing of function parameter attributes

---

Sources/MockingbirdCli/Interface/Installer.swift

If the generator crashes or is interrupted, the cache buster file is never removed which means Xcode will cache the failed result until the project is cleaned.

Remove cache buster file before generating mocks

---

Sources/MockingbirdGenerator/Generator/Templates/MockableTypeInitializerTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/Primitives/FunctionDefinitionTemplate.swift
Sources/MockingbirdTestsHost/ExternalModuleTypes.swift

**Stack:**
📚 #251 ***← [3/y] Fix unavailable generic protocol mock initializer***
Mock initializer functions were not migrated to use the new templates in 0.18. This caused unavailable generic protocols (e.g. inheriting from an opaque external type) to generate malformed output.
```swift
// error: Consecutive statements on a line must be separated by ';'
public enum InheritingMissingExternalClassGeneric<T> {
}@available(*, unavailable, message: …
```

[3/y] Fix unavailable generic protocol mock initializer

---

Sources/MockingbirdCli/Interface/Handlers/Generator+Pipeline.swift
Sources/MockingbirdGenerator/Generator/Operations/FileGenerator.swift
Sources/MockingbirdGenerator/Generator/Operations/GenerateFileOperation.swift

**Stack:**
📚 #252 ***← [4/y] Show help message no mockable types are generated***
Thunk pruning can be confusing now that `omit` is the default method. To improve the developer onboarding experience, we can generate an inline comment when there are no mocked types available.

[4/y] Show help message no mockable types are generated

---

Mockingbird.xcodeproj/project.pbxproj
README-0.19.md
Sources/MockingbirdCli/Interface/Commands/Generate.swift
Sources/MockingbirdCli/Interface/Handlers/Generator.swift
Sources/MockingbirdCli/Interface/Handlers/Installer.swift
Sources/MockingbirdCli/Utils/String+Regex.swift

**Stack:**
📚 #253 ***← [5/y] Improve support for configuring SPM Xcode projects***
Current support for Swift Package Manager is a bit rough for both Xcode project and package manifest setups, and we lack clear guidance for the latter in the README (see #236).
One major issue is that using the configurator against an SwiftPM Xcode project links the CLI in derived data with a home-relative path, which isn’t guaranteed to be portable between development environments. Another …

[5/y] Improve support for configuring SPM Xcode projects

---

Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdFramework/Objective-C/Bridge/include/MKBTestUtils.h
Sources/MockingbirdFramework/Objective-C/Bridge/sources/MKBTestUtils.m
Sources/MockingbirdFramework/Objective-C/InvocationHandlers/MKBObjectInvocationHandler.m
Sources/MockingbirdFramework/Stubbing/StubbingContext+ObjC.swift
Sources/MockingbirdTestsHost/Optionals.swift
Tests/MockingbirdTests/Framework/DynamicSwiftTests.swift
Tests/MockingbirdTests/Framework/OptionalsTests.swift

**Stack:**
📚 #248 [9/y] Fix nested optional codegen
📚 #247 [8/y] Fix wildcard arg matching for Obj-C param types
📚 #246 ***← [7/y] Fix stubbing nil values in Obj-C mocks***
Fixes #238 where stubbing a `nil` value for Objective-C mocks would incorrectly implicitly bridge to `NSNull`. Rather than passing a raw `nil` to Objective-C, we can instead use a custom representation `NilValue` and handle that case …

[7/y] Fix stubbing nil values in Obj-C mocks

---

Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdFramework/Matching/TypeFacade.swift
Sources/MockingbirdFramework/Objective-C/Bridge/include/MKBTypeFacade.h
Sources/MockingbirdFramework/Objective-C/Bridge/sources/MKBTypeFacade.m
Sources/MockingbirdFramework/Objective-C/InvocationHandlers/MKBObjectInvocationHandler.m
Sources/MockingbirdTestsHost/ObjCParameters.swift
Tests/MockingbirdTests/Framework/ObjectiveCParameterTests.swift

**Stack:**
📚 #248 [9/y] Fix nested optional codegen
📚 #247 ***← [8/y] Fix wildcard arg matching for Obj-C param types***
📚 #246 [7/y] Fix stubbing nil values in Obj-C mocks
Dynamic mocking (introduced in 0.18) changed how Objective-C parameter types are faked for wildcard argument matching. To support Objective-C mocking, argument matchers for `NSObjectProtocol` parameters no longer create type facades that go …

[8/y] Fix wildcard arg matching for Obj-C param types

---

Sources/MockingbirdGenerator/Generator/Templates/ThunkTemplate.swift
Sources/MockingbirdTestsHost/Optionals.swift

**Stack:**
📚 #248 ***← [9/y] Fix nested optional codegen***
📚 #247 [8/y] Fix wildcard arg matching for Obj-C param types
📚 #246 [7/y] Fix stubbing nil values in Obj-C mocks
This fixes the implicit type coercion when bridging nested optional property setters to `Any?` for dynamic mocking.
```swift
// warning: Expression implicitly coerced from 'String??' to 'Any?'
if let mkbImpl = mkbImpl as? (Any?) -> Any? { …
```

[9/y] Fix nested optional codegen

---

README.md
Sources/MockingbirdCli/Info.plist
Sources/MockingbirdCommon/Version.swift
Sources/MockingbirdFramework/Info.plist
Sources/MockingbirdGenerator/Info.plist

**Stack:**
📚 #259 ***← [4/x] Bump versions to 0.19.0***
📚 #258 [3/x] Codemod Xcode-generated file header comments
📚 #257 [2/x] Migrate to DocC for API reference docs
📚 #256 [1/x] Clean up automation pipeline
Cut release for 0.19.0.
```console
$ Sources/MockingbirdCli/buildAndRun.sh --version
[94/94] Build complete!
0.19.0
```

[4/x] Bump versions to 0.19.0

---

.github/workflows/release.yml
Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdAutomationCli/Commands/Build.swift
Sources/MockingbirdAutomationCli/Commands/BuildSupportingSources.swift

📚 #266 [6/x] Update example projects to use 0.19.1
📚 #265 [5/x] Fix support for Swift library evolution
📚 #264 [4/x] Fix configurator relative path handling
📚 #263 [3/x] Fix package manager integrations
📚 #261 ***← [2/x] Archive supporting sources in release workflow***
Adds a step to the build release artifacts job to archive the supporting sources at `Sources/MockingbirdSupport` along with the license file.
Building a supporting source archive with `--archive` creates a ZIP that includes the `LICENSE.md` and can be inflated.
```console
% Sources/MockingbirdAutomationCli/buildAndRun.sh build supporting
[8/8] Build complete!
error: You must specify an archive location when building supporting sources
% …
```

[2/x] Archive supporting sources in release workflow

---

.github/workflows/ci.yml
Mockingbird.xcodeproj/project.pbxproj
MockingbirdFramework.podspec
Package.swift
Sources/MockingbirdAutomation/Interop/Git.swift
Sources/MockingbirdAutomation/Interop/SwiftPackage.swift
Sources/MockingbirdAutomation/Utilities/Path+Backup.swift
Sources/MockingbirdAutomationCli/Commands/BuildFramework.swift
Sources/MockingbirdAutomationCli/Commands/TestExampleProject.swift
Sources/MockingbirdFramework/Utilities/ExportedModules.swift
mockingbird

📚 #266 [6/x] Update example projects to use 0.19.1
📚 #265 [5/x] Fix support for Swift library evolution
📚 #264 [4/x] Fix configurator relative path handling
📚 #263 ***← [3/x] Fix package manager integrations***
📚 #261 [2/x] Archive supporting sources in release workflow
Changes to the project structure and build pipeline caused most of the package manager integrations to break. The current package manager tests aren’t E2E (they only check if the spec / package definition validates), and the more robust example project tests don’t run against the current revision.
This PR fixes the regressions and improves the example project tests, allowing them to build against HEAD. The goal is to keep the example projects portable such that they can be …

[3/x] Fix package manager integrations

---

Sources/MockingbirdCli/Arguments/InferableArgument.swift
Sources/MockingbirdCli/Commands/Configure.swift
Sources/MockingbirdCli/Commands/Generate.swift
Sources/MockingbirdCli/Handlers/Installer.swift

📚 #266 [6/x] Update example projects to use 0.19.1
📚 #265 [5/x] Fix support for Swift library evolution
📚 #264 ***← [4/x] Fix configurator relative path handling***
📚 #263 [3/x] Fix package manager integrations
📚 #261 [2/x] Archive supporting sources in release workflow
The configurator produces incorrect paths when run from an Xcode project directory that differs from the test target project that’s being configured. This PR fixes the issue by allowing the configurator to pass a working directory to the generator so that argument values are inferred from the correct base path.
Running `configure` from the Mockingbird source root while configuring the Carthage example project produces the correct supporting sources path.
```console …
```

[4/x] Fix configurator relative path handling

---

Mockingbird.xcodeproj/project.pbxproj
Mockingbird.xcodeproj/xcconfigs/FrameworkBase.xcconfig
MockingbirdFramework.podspec
Sources/Documentation/Mockingbird.docc/Pages/Essentials/Verification.md
Sources/MockingbirdAutomation/Interop/Carthage.swift
Sources/MockingbirdAutomationCli/Resources/XcodeSchemes/MockingbirdAutomation.xcscheme
Sources/MockingbirdAutomationCli/Resources/XcodeSchemes/MockingbirdAutomationCli.xcscheme
Sources/MockingbirdAutomationCli/Resources/XcodeSchemes/MockingbirdCli.xcscheme
Sources/MockingbirdFramework/Objective-C/Bridge/include/MKBTestExpectation.h
Sources/MockingbirdFramework/Objective-C/Bridge/include/Mockingbird.h
Sources/MockingbirdFramework/Objective-C/Bridge/sources/MKBTestExpectation.m
Sources/MockingbirdFramework/Verification/AsyncVerification.swift
Sources/MockingbirdFramework/Verification/ExpectationGroup.swift
Tests/MockingbirdTests/Framework/AsyncVerificationTests.swift

📚 #266 [6/x] Update example projects to use 0.19.1
📚 #265 ***← [5/x] Fix support for Swift library evolution***
📚 #264 [4/x] Fix configurator relative path handling
📚 #263 [3/x] Fix package manager integrations
📚 #261 [2/x] Archive supporting sources in release workflow
Module stability is currently broken despite enabling the `BUILD_LIBRARIES_FOR_DISTRIBUTION` build setting which prevents using an “old” version of Mockingbird.framework if it hasn’t been compiled for the current toolchain and Swift version. After some investigation, it’s due to a known issue since [Xcode 11.2](https://developer.apple.com/documentation/xcode-release-notes/xcode-11_2-release-notes):
> If a module is built with `BUILD_LIBRARIES_FOR_DISTRIBUTION` and contains a …

[5/x] Fix pre-built library evolution and testability

---

Examples/CarthageExample/Cartfile
Examples/CarthageExample/Cartfile.resolved
Examples/CarthageExample/CarthageExample.xcodeproj/project.pbxproj
Examples/CarthageExample/MockingbirdSupport/LICENSE.md
Examples/CocoaPodsExample/CocoaPodsExample.xcodeproj/project.pbxproj
Examples/CocoaPodsExample/MockingbirdSupport/LICENSE.md
Examples/CocoaPodsExample/Podfile
Examples/CocoaPodsExample/Podfile.lock
Examples/SPMPackageExample/MockingbirdSupport/LICENSE.md
Examples/SPMPackageExample/Package.resolved
Examples/SPMPackageExample/Package.swift
Examples/SPMProjectExample/MockingbirdSupport/LICENSE.md
Examples/SPMProjectExample/SPMProjectExample.xcodeproj/project.pbxproj
Examples/SPMProjectExample/SPMProjectExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/MockingbirdAutomation/Interop/SwiftPackage.swift
Sources/MockingbirdAutomation/Interop/XcodeBuild.swift
Sources/MockingbirdAutomationCli/Commands/TestExampleProject.swift

📚 #266 ***← [6/x] Update example projects to use 0.19.1***
📚 #265 [5/x] Fix support for Swift library evolution
📚 #264 [4/x] Fix configurator relative path handling
📚 #263 [3/x] Fix package manager integrations
📚 #261 [2/x] Archive supporting sources in release workflow
Bumps the example projects to use the 0.19 release train. Mostly important due to the switch from `install` to `configure`.
Example project tests pass locally and on CI.

[6/x] Update example projects to use 0.19.1

---

.github/PULL_REQUEST_TEMPLATE.md

Moves the pull request template to `.github/PULL_REQUEST_TEMPLATE.md` so that query parameters aren’t needed to display it ([GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)).
Pull request template is displayed on stage:

[EZ] Fix GitHub pull request template

---

Mockingbird.xcodeproj/project.pbxproj
Sources/MockingbirdFramework/Objective-C/Bridge/include/MKBTestUtils.h
Sources/MockingbirdFramework/Objective-C/Bridge/sources/MKBTestUtils.m
Sources/MockingbirdFramework/Stubbing/StubbingContext+ObjC.swift
Sources/MockingbirdFramework/Utilities/Optional+Extensions.swift

📚 #275 [5/x] Clean up Synchronized wrapper
📚 #274 [4/x] Fix nested optional property and Obj-C types
📚 #273 [3/x] Improve compile-time checks for Swift mocks
📚 #272 ***← [2/x] Remove Obj-C based nil check***
📚 #271 [1/x] Add Algolia DocSearch to the documentation
Removes the `MKBCheckIfTypeErasedNil` workaround in favor of a simple protocol extension on `Optional`.
```swift
func test<T>(_ value: T) -> Bool {
return (value as? Nullable)?.isNil ?? false
}
test(Optional<Int>(nil))  // true
test(Optional<Int>(42))   // false
test(42)   // false
```

[2/x] Remove Obj-C based nil check

---

Sources/MockingbirdFramework/Mocking/Declaration.swift
Sources/MockingbirdFramework/Mocking/Mocking.swift
Sources/MockingbirdFramework/Stubbing/Stubbing.swift
Sources/MockingbirdFramework/Utilities/Optional+Extensions.swift
Sources/MockingbirdFramework/Verification/Verification.swift

📚 #275 [5/x] Clean up Synchronized wrapper
📚 #274 [4/x] Fix nested optional property and Obj-C types
📚 #273 ***← [3/x] Improve compile-time checks for Swift mocks***
📚 #272 [2/x] Remove Obj-C based nil check
📚 #271 [1/x] Add Algolia DocSearch to the documentation
The Objective-C overloads introduced in 0.18 makes it difficult for the Swift compiler to choose the correct branch when type checking `given` expressions. This is exacerbated with the stubbing operator which can provide incorrect constraints on the return type, preventing implicit bridging of optionals and Foundation types.
```swift
protocol Foo {
var nonOptional: String { get }
var optional: String? { get }
var bridged: NSString { get }
}
var stored: String! = "foo"
given(myMock.nonOptional) ~> stored  // Compiler fails to …
```

[3/x] Improve compile-time checks for Swift mocks

---

Sources/MockingbirdCommon/Synchronized.swift

📚 #275 ***← [5/x] Clean up Synchronized wrapper***
📚 #274 [4/x] Fix nested optional property and Obj-C types
📚 #273 [3/x] Improve compile-time checks for Swift mocks
📚 #272 [2/x] Remove Obj-C based nil check
📚 #271 [1/x] Add Algolia DocSearch to the documentation
Minor cleanup of the `Synchronized` wrapper to make the behavior better conform to a standard RW lock. Once the migration to Swift Concurrency is complete we should remove this in favor of actors.
- CI tests pass

[5/x] Clean up Synchronized wrapper

---

.github/workflows/ci.yml
.github/workflows/release.yml
Sources/MockingbirdFramework/Mocking/MockingContext.swift
Sources/MockingbirdFramework/Stubbing/Stubbing.swift
Sources/MockingbirdTestsHost/AsyncMethods.swift
Tests/MockingbirdTests/Framework/StubbingAsyncTests.swift

📚 #287 [5/y] Improve static mocking APIs
📚 #286 [4/y] Enable mocking sources in test bundles
📚 #285 [3/y] Fix read-only subscripts
📚 #284 [2/y] Fix warnings in throwing initializers
📚 #283 ***← [1/y] Add backwards compatibility with Swift 5.5***
Adding support for concurrency implicitly increased our minimum Swift target to 5.5.2. Trying to consume the framework on an older toolchain like Xcode 13.1 (Swift 5.5) would fail to compile. I wrapped all async/await testing interfaces in `#if swift(>=5.5.2)` compilation conditions. Technically we could target Swift 5.5 for concurrency which has different platform targets (no support for older OSes), but this increases the complexity of both the framework interface and the testing matrix we need to use without much benefit.
Added CI tests that …

[1/y] Add backwards compatibility with Swift 5.5

---

Mockingbird.xcodeproj/xcconfigs/MockingbirdTests.xcconfig
Sources/MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/ThunkTemplate.swift
Tests/MockingbirdTests/Framework/Utilities/XFailTestFailer.swift

📚 #287 [5/y] Improve static mocking APIs
📚 #286 [4/y] Enable mocking sources in test bundles
📚 #285 [3/y] Fix read-only subscripts
📚 #284 ***← [2/y] Fix warnings in throwing initializers***
📚 #283 [1/y] Add backwards compatibility with Swift 5.5
Fixes compile-time warnings in mocked initializer declarations like the one below:
`No calls to throwing functions occur within 'try' expression`
Enabled “treat warnings as errors” on the tests target so that the CI can catch regressions in generator warnings.

[2/y] Fix warnings in throwing initializers

---

Sources/MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
Sources/MockingbirdGenerator/Parser/Models/Method.swift
Sources/MockingbirdTestsHost/Subscripts.swift
Tests/MockingbirdTests/Framework/SubscriptTests.swift

📚 #287 [5/y] Improve static mocking APIs
📚 #286 [4/y] Enable mocking sources in test bundles
📚 #285 ***← [3/y] Fix read-only subscripts***
📚 #284 [2/y] Fix warnings in throwing initializers
📚 #283 [1/y] Add backwards compatibility with Swift 5.5
Read-only subscripts were incorrectly generating setter thunks which weren’t caught by the test suite due to the generic `Equatable` overload. This adds the `readonly` attribute as needed when parsing subscript methods using similar logic as properties.
Closes #281
Fixed read-only subscript tests and added an additional case for setters marked as (file)private.

[3/y] Fix read-only subscripts

---

Sources/MockingbirdCli/Handlers/Generator.swift
Sources/MockingbirdCli/main.swift
Sources/MockingbirdGenerator/Parser/Operations/ExtractSourcesOperation.swift
Sources/MockingbirdGenerator/Parser/Operations/FindMockedTypesOperation.swift
Sources/MockingbirdGenerator/Utilities/Log.swift
Sources/MockingbirdGenerator/Utilities/Path+WriteUtf8Strings.swift

📚 #287 [5/y] Improve static mocking APIs
📚 #286 ***← [4/y] Enable mocking sources in test bundles***
📚 #285 [3/y] Fix read-only subscripts
📚 #284 [2/y] Fix warnings in throwing initializers
📚 #283 [1/y] Add backwards compatibility with Swift 5.5
It’s uncommon, but possible, to need to mock types defined in a test bundle. For example, one use case is supplying a common set of default implementations for partial mocking. A non-typical case is mocking types in test bundle A and using them in test bundle B, which is straightforward to set up in SwiftPM / JSON project descriptions but not so much with an Xcode project.
To simplify the automatic setup process and reduce potential user errors, the configurator will continue to validate that the configuration target is a test bundle and each …

[4/y] Enable mocking sources in test bundles

---

Sources/Documentation/Mockingbird.docc/Pages/Essentials/Mocking.md
Sources/Documentation/Mockingbird.docc/Pages/Essentials/Stubbing.md
Sources/Documentation/Mockingbird.docc/Pages/Essentials/Verification.md
Sources/Documentation/Mockingbird.docc/Pages/Meta/Feature-Comparison.md
Sources/Documentation/Mockingbird.docc/Pages/Meta/Internal.md
Sources/Documentation/Mockingbird.docc/Pages/Meta/Known-Limitations.md
Sources/MockingbirdFramework/Mocking/Declaration.swift
Sources/MockingbirdFramework/Mocking/GenericStaticMockContext.swift
Sources/MockingbirdFramework/Mocking/Mock.swift
Sources/MockingbirdFramework/Mocking/Mocking.swift
Sources/MockingbirdFramework/Stubbing/Stubbing.swift
Sources/MockingbirdFramework/Verification/AsyncVerification.swift
Sources/MockingbirdFramework/Verification/Verification.swift
Sources/MockingbirdGenerator/Generator/Operations/FileGenerator.swift
Sources/MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/MockableTypeTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/ThunkTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/VariableTemplate.swift
Tests/MockingbirdTests/Framework/GenericsTests.swift
Tests/MockingbirdTests/Framework/StubbingTests.swift

📚 #287 ***← [5/y] Improve static mocking APIs***
📚 #286 [4/y] Enable mocking sources in test bundles
📚 #285 [3/y] Fix read-only subscripts
📚 #284 [2/y] Fix warnings in throwing initializers
📚 #283 [1/y] Add backwards compatibility with Swift 5.5
Mocking static members is currently a bit cumbersome because it requires referencing the `staticMock` property when stubbing or verifying. Now that the mocking and stubbing contexts live under a single context object we can store a static `mockingbirdContext` instance instead of a `Mock`. As a result, the testing API is a lot simpler and works directly on the metatype instance.
```swift
protocol Bird {
static var species: String { get }
}
let birdType = type(of: mock(Bird.self))
given(birdType.species).willReturn("Mimus polyglottos") …
```

[5/y] Improve static mocking APIs

---

Sources/MockingbirdCli/Commands/Generate.swift
Sources/MockingbirdCli/Handlers/Generator+Pipeline.swift
Sources/MockingbirdCli/Handlers/Generator+PruningPipeline.swift
Sources/MockingbirdCli/Handlers/Generator.swift
Sources/MockingbirdGenerator/Parser/Operations/CheckCacheOperation.swift
Sources/MockingbirdGenerator/Parser/Project/TestTarget.swift
mockingbird

📚 #279 [2/x] Fix optional members in Obj-C protocols
📚 #278 ***← [1/x] Fix cross-project cache invalidation***
Test and source target caching is improperly invalidated when generating mocks for targets outside of the current test target context. The caching issues are compounded when generating mocks for multiple projects in the same test target. This PR fixes the caching behavior for cross-project mocking setups.
Validated that the test and source target caches are invalidated iff the inputs are changed.

[1/x] Fix cross-project cache invalidation

---

Mockingbird.xcodeproj/project.pbxproj
Mockingbird.xcodeproj/xcconfigs/MockingbirdFramework.xcconfig
Mockingbird.xcodeproj/xcconfigs/MockingbirdGenerator.xcconfig
Sources/MockingbirdFramework/Mocking/Mocking.swift
Sources/MockingbirdFramework/Objective-C/MKBConcreteMock.m
Sources/MockingbirdFramework/Stubbing/InvocationForwarding.swift
Sources/MockingbirdGenerator/Generator/Templates/MethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/SubscriptMethodTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/ThunkTemplate.swift
Sources/MockingbirdGenerator/Generator/Templates/VariableTemplate.swift
Sources/MockingbirdGenerator/Parser/Models/TypeAttributes.swift
Sources/MockingbirdTestsHost/ObjCProtocol.swift
Tests/MockingbirdTests/Framework/ObjectiveCProtocolTests.swift
Tests/MockingbirdTests/Framework/Utilities/BaseTestCase.swift

📚 #279 ***← [2/x] Fix optional members in Obj-C protocols***
📚 #278 [1/x] Fix cross-project cache invalidation
Generating Swift mocks for Objective-C annotated protocols with optional members regressed in 0.18 due to invocation forwarding for partial mocks. This PR allows the generator to explicitly handle optional members and improves the overall Objective-C compatibility.
Added an additional test case for Objective-C protocols.

[2/x] Fix optional members in Obj-C protocols

---

Sources/MockingbirdCli/Info.plist
Sources/MockingbirdCommon/Version.swift
Sources/MockingbirdFramework/Info.plist
Sources/MockingbirdGenerator/Info.plist

Bumps the framework and generator versions to 0.20.0.
CI tests pass.

Bump versions to 0.20.0
